#!usr/bin/env bash
DIRNAME=$1
EXTTYPE1=$2
EXTTYPE2=$3
EXTTYPE3=$4

COUNT1=0
COUNT2=0
COUNT3=0

for file in $DIRNAME/*
do
case $file in 
*.$2 )
	COUNT1=$[COUNT1+1];;
*.$3 )
	COUNT2=$[COUNT2+1];;
*.$4 )
	COUNT3=$[COUNT3+1];;
esac
done
echo "$2 count: " $COUNT1
echo "$3 count: " $COUNT2
echo "$4 count: " $COUNT3
